import Provider from "@/context/Provider";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import type { NextFont } from "next/dist/compiled/@next/font";
import type { JSX } from "react";

const josefin: NextFont = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={`${josefin.className} antialiased bg-background`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
